development:
  cloud_name: eventic
  api_key: '488614995595858'
  api_secret: XBS0MLnUewJkdilrJc3ct9HwUAM
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: eventic
  api_key: '488614995595858'
  api_secret: XBS0MLnUewJkdilrJc3ct9HwUAM
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: eventic
  api_key: '488614995595858'
  api_secret: XBS0MLnUewJkdilrJc3ct9HwUAM
  enhance_image_tag: true
  static_file_support: false
